### ISSUE TITLE
api not working

### ISSUE THREAD

**Issue by zonalagu** [bartleyg/my-spotify-canvas#4]
Hi there! you've been built awesome website with spotify canvas. 

I've been trying to deploy my own with this repo, then i got some error. i thought this error because enviroment variables, my env is stored on vercel dashboard ui like this and delete the `now.json`.

![SCR-20220509-pmp](https://user-images.githubusercontent.com/46441270/167392685-59b3c2ba-420e-4ee8-bb94-8a39dff6c77a.png)

then i deploy and check the console i got this

![SCR-20220509-pm1](https://user-images.githubusercontent.com/46441270/167392997-4aba3da3-8db9-4313-94b7-c07af2d0dc81.png)

![SCR-20220509-pli](https://user-images.githubusercontent.com/46441270/167393180-a6f1c4ae-68b6-4d70-903a-571b2c035052.png)

logs on vercel function

![image](https://user-images.githubusercontent.com/46441270/167393610-cf2dbc9d-ec83-47a7-af0a-54492d68e63b.png)

before i used this project, i've tested my `.env` on my own project and well-worked. 

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/46441270/167394431-a078a994-5129-4428-9845-7c53394f4e15.png">

thank you for stopping by. have a nice day!

**Comment by bartleyg** [comment]
There was a bug indeed only in the error path of those API requests in the logging from a copy/paste error. Pull from master and that will hopefully help with debugging. Those lines are only hit if there's an error from Spotify's API, so probably your tokens/secrets are not getting pulled into your project correctly. Now/Zeit/Vercel keeps changing how they do things over the years, so you may have to change something to deploy correctly.

**Comment by coldrdy** [comment]
ah, the problem is solved now. i created new app and get refresh token [here](https://getyourspotifyrefreshtoken.herokuapp.com/) with `user-read-recently-played` scope.

thank you 🙌🏻
